<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<RootNamespace>StarterKit.Identity.Contracts</RootNamespace>
	<AssemblyName>StarterKit.Identity.Contracts</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Lightsoft.Result" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Shared\Shared.csproj" />
  </ItemGroup>

</Project>
