<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>StarterKit.ModuleName.Contracts</RootNamespace>
    <AssemblyName>StarterKit.ModuleName.Contracts</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Shared\Shared.csproj" />
  </ItemGroup>

</Project>
