<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <ManagePackageVersionsCentrally>false</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="$(AspnetVersion)">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="$(AspnetVersion)">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="$(AspnetVersion)" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="$(AspnetVersion)" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="$(AspnetVersion)" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="$(AspnetVersion)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Approval.Api\Approval.Api.csproj" />
    <ProjectReference Include="..\..\Identity.Api\Identity.Api.csproj" />
    <ProjectReference Include="..\..\Infrastructure\Infrastructure.csproj" />
    <ProjectReference Include="..\..\LeaveManagement.Api\LeaveManagement.Api.csproj" />
    <ProjectReference Include="..\..\Organization.Api\Organization.Api.csproj" />
    <ProjectReference Include="..\..\Persistence\Persistence.csproj" />
    <ProjectReference Include="..\..\Shared\Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
	<Content Update="@(Content)">
	  <Visible Condition="'%(NuGetItemType)' == 'Content'">false</Visible>
	</Content>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Approval\" />
    <Folder Include="Identity\" />
    <Folder Include="LeaveManagement\" />
    <Folder Include="Organization\" />
  </ItemGroup>

</Project>
