<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<RootNamespace>StarterKit.Identity.Api</RootNamespace>
	<AssemblyName>StarterKit.Identity.Api</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="Lightsoft.ActiveDirectory" />
    <PackageReference Include="Lightsoft.SharedKernel" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Identity.Contracts\Identity.Contracts.csproj" />
    <ProjectReference Include="..\Infrastructure\Infrastructure.csproj" />
    <ProjectReference Include="..\Persistence\Persistence.csproj" />
  </ItemGroup>

</Project>
