<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
	<RootNamespace>Monolith.Blazor</RootNamespace>
	<AssemblyName>Monolith.BlazorComponents</AssemblyName>
	<ManagePackageVersionsCentrally>false</ManagePackageVersionsCentrally>

	<!-- *** IMPORTANT: JavaScript / CSS minification *** -->
	<CssMinifyEnabled>true</CssMinifyEnabled>
	<JavaScriptMinifyEnabled>true</JavaScriptMinifyEnabled>
	<JavaScriptMinifier>Closure</JavaScriptMinifier>
	<!-- or Node-based if installed -->
  </PropertyGroup>

  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
	<PackageReference Include="Lightsoft.MudBlazor" Version="9.0.0-beta5" />
	<PackageReference Include="Microsoft.AspNetCore.Components.Authorization" Version="$(AspnetVersion)" />
	<PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="$(AspnetVersion)" />
	<PackageReference Include="MudBlazor.ThemeManager" Version="4.0.0" />
	<PackageReference Include="QRCoder" Version="1.8.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HttpApi.Client\HttpApi.Client.csproj" />
  </ItemGroup>

  <Target Name="MinifyFirst" BeforeTargets="BeforeBuild" Condition="'$(Configuration)'=='Release'">
	<!-- Delete old JS/CSS minified files -->
	<Delete Files="$(ProjectDir)wwwroot\site.min.js" />
	<Delete Files="$(ProjectDir)wwwroot\site.min.css" />
	<!-- Compile and minify JS/CSS files -->
	<Exec Command="powershell -ExecutionPolicy Bypass -File $(ProjectDir)MinifyInOne.ps1" LogStandardErrorAsError="true" />
  </Target>

</Project>
