<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<RootNamespace>StarterKit.Notifications.Api</RootNamespace>
	<AssemblyName>StarterKit.Notifications.Api</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Identity.Contracts\Identity.Contracts.csproj" />
    <ProjectReference Include="..\Infrastructure\Infrastructure.csproj" />
    <ProjectReference Include="..\Notifications.Contracts\Notifications.Contracts.csproj" />
    <ProjectReference Include="..\Persistence\Persistence.csproj" />
  </ItemGroup>

</Project>
