<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<RootNamespace>StarterKit.LeaveManagement.Api</RootNamespace>
	<AssemblyName>StarterKit.LeaveManagement.Api</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="LeaveManagement.Tests" />
  </ItemGroup>

  <ItemGroup>
	<PackageReference Include="Lightsoft.AspNetCore.Authorization" />
	<PackageReference Include="Lightsoft.EntityFrameworkCore" />
	<PackageReference Include="Lightsoft.Mediator" />
	<PackageReference Include="Lightsoft.Result" />
	<PackageReference Include="Mapster" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Approval.Contracts\Approval.Contracts.csproj" />
    <ProjectReference Include="..\Infrastructure\Infrastructure.csproj" />
    <ProjectReference Include="..\LeaveManagement.Contracts\LeaveManagement.Contracts.csproj" />
    <ProjectReference Include="..\Organization.Contracts\Organization.Contracts.csproj" />
    <ProjectReference Include="..\Persistence\Persistence.csproj" />
  </ItemGroup>

</Project>
