<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<RootNamespace>StarterKit.Organization.Api</RootNamespace>
	<AssemblyName>StarterKit.Organization.Api</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Organization.Tests" />
  </ItemGroup>

  <ItemGroup>
	<PackageReference Include="Lightsoft.AspNetCore.Authorization" />
	<PackageReference Include="Lightsoft.EntityFrameworkCore" />
	<PackageReference Include="Lightsoft.Mediator" />
	<PackageReference Include="Lightsoft.Result" />
	<PackageReference Include="Mapster" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Identity.Contracts\Identity.Contracts.csproj" />
    <ProjectReference Include="..\Infrastructure\Infrastructure.csproj" />
    <ProjectReference Include="..\Organization.Contracts\Organization.Contracts.csproj" />
    <ProjectReference Include="..\Persistence\Persistence.csproj" />
  </ItemGroup>

</Project>
