<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <ManagePackageVersionsCentrally>false</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
	<PackageReference Include="Microsoft.EntityFrameworkCore" Version="$(AspnetVersion)" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="$(AspnetVersion)" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="$(AspnetVersion)">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="$(AspnetVersion)">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="$(AspnetVersion)" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="$(AspnetVersion)" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="$(AspnetVersion)" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="$(AspnetVersion)" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.2" />
	<PackageReference Include="Lightsoft.Serilog" Version="1.0.0.3" />
  </ItemGroup>

  <ItemGroup>
	<Content Update="@(Content)">
		<Visible Condition="'%(NuGetItemType)' == 'Content'">false</Visible>
	</Content>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Modules.Catalog\Modules.Catalog.csproj" />
    <ProjectReference Include="..\..\Modules.Identity\Modules.Identity.csproj" />
  </ItemGroup>

</Project>
